name: cicd-workflow with Slack integration
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Send Hello World and Job Status to Slack
      run: |
        STATUS=${{ job.status }}
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello World! The job status is: '"$STATUS"'."}' $SLACK_WEBHOOK_URL
