name: cicd-workflow with slack integration
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Notify Slack - Build started
      uses: slackapi/slack-github-action@v1
      with:
        status: starting
        channel: '#all-mycompany'
        text: 'Starting Docker Build image...'
      if: always()

    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t my-docker-repo .

    - name: Notify Slack - Build finished
      uses: slackapi/slack-github-action@v1
      with:
        channel: '#all-mycompany'
        status: ${{ job.status }}
        text: |
          Docker Build finished with status: ${{ job.status }}
          View details: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
      if: always()
