name: cicd-workflow with slack integration
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: slackapi/slack-github-action@v1
      with:
        status: starting
        channel: '#all-mycompany'
        text: 'Starting Docker Build image...'  # Ensure the message is provided here
      if: always()
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build -t my-docker-repo .
    - uses: slackapi/slack-github-action@v1
      with:
        channel: '#all-mycompany'
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        text: 'Docker Build Finished with status: ${{ job.status }}'  # Provide a message here as well
      if: always()
